"use client";

// deps: ogl
import { Mesh, Program, Renderer, Triangle } from "ogl";
import { useEffect, useRef } from "react";

export interface FaultyTerminalProps { scale?: number; gridMul?: [number, number]; digitSize?: number; timeScale?: number; pause?: boolean; scanlineIntensity?: number; glitchAmount?: number; flickerAmount?: number; noiseAmp?: number; chromaticAberration?: number; dither?: number | boolean; curvature?: number; tint?: string; mouseReact?: boolean; mouseStrength?: number; pageLoadAnimation?: boolean; brightness?: number; }
const vertex=`attribute vec2 position;attribute vec2 uv;varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,0.,1.);}`;
const fragment=`precision mediump float;varying vec2 vUv;uniform float uTime,uScale,uDigit,uScan,uGlitch,uFlicker,uNoise,uCA,uDither,uCurve,uMouseStrength,uLoad,uBrightness;uniform vec2 uResolution,uGrid,uMouse;uniform vec3 uTint;uniform bool uUseMouse;float hash(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);}float glyph(vec2 p){vec2 grid=uGrid*15.;vec2 cell=floor(p*grid)/grid;p=fract(p*grid)*uDigit;float n=hash(cell+floor(uTime*.5));if(uUseMouse){float d=distance(cell,uMouse*uScale);n+=exp(-d*8.)*uMouseStrength*5.;}vec2 q=abs(fract(p*5.)-.5);float strokes=step(q.x,.16)+step(q.y,.12);return step(.56,n)*clamp(strokes,0.,1.);}vec3 color(vec2 p){float line=(.7+.3*step(.2,fract(p.y*70.+uTime*8.)))*uScan;float shift=sin(p.y*20.+uTime)*.0125*uGlitch*uFlicker;float g=glyph(p+vec2(shift,0.));return vec3(g*line);}void main(){vec2 uv=vUv;if(uCurve>0.){vec2 q=uv*2.-1.;q*=1.+uCurve*dot(q,q);uv=q*.5+.5;}vec2 p=uv*uScale;vec3 col=color(p);if(uCA>0.){vec2 ca=vec2(uCA)/uResolution;col.r=color(p+ca).r;col.b=color(p-ca).b;}col*=uTint*uBrightness;col+=(hash(gl_FragCoord.xy)-.5)*uDither*.004;gl_FragColor=vec4(col*uLoad,1.);}`;
const hex=(color:string)=>{const h=color.replace("#","");const value=parseInt(h.length===3?h.split("").map(x=>x+x).join(""):h,16);return new Float32Array([((value>>16)&255)/255,((value>>8)&255)/255,(value&255)/255]);};
export function FaultyTerminal({scale=1.5,gridMul=[2,1],digitSize=1.2,timeScale=1,pause=false,scanlineIntensity=1,glitchAmount=1,flickerAmount=1,noiseAmp=1,chromaticAberration=0,dither=0,curvature=0,tint="#ffffff",mouseReact=true,mouseStrength=.5,pageLoadAnimation=false,brightness=1}:FaultyTerminalProps){const hostRef=useRef<HTMLDivElement>(null);useEffect(()=>{const host=hostRef.current;if(!host)return;const renderer=new Renderer({dpr:Math.min(2,window.devicePixelRatio||1)}),gl=renderer.gl,res=new Float32Array(2),mouse=new Float32Array([.5,.5]);gl.clearColor(0,0,0,1);const program=new Program(gl,{vertex,fragment,uniforms:{uTime:{value:0},uResolution:{value:res},uScale:{value:scale},uGrid:{value:new Float32Array(gridMul)},uDigit:{value:digitSize},uScan:{value:scanlineIntensity},uGlitch:{value:glitchAmount},uFlicker:{value:flickerAmount},uNoise:{value:noiseAmp},uCA:{value:chromaticAberration},uDither:{value:typeof dither==="boolean"?(dither?1:0):dither},uCurve:{value:curvature},uTint:{value:hex(tint)},uMouse:{value:mouse},uMouseStrength:{value:mouseStrength},uUseMouse:{value:mouseReact},uLoad:{value:pageLoadAnimation?0:1},uBrightness:{value:brightness}}});const mesh=new Mesh(gl,{geometry:new Triangle(gl),program});Object.assign(gl.canvas.style,{position:"absolute",inset:"0",width:"100%",height:"100%"});host.appendChild(gl.canvas);const resize=()=>{renderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight));res[0]=gl.drawingBufferWidth;res[1]=gl.drawingBufferHeight;};resize();const ro=new ResizeObserver(resize);ro.observe(host);const move=(event:PointerEvent)=>{const r=host.getBoundingClientRect();mouse[0]=(event.clientX-r.left)/r.width;mouse[1]=1-(event.clientY-r.top)/r.height;};if(mouseReact)host.addEventListener("pointermove",move,{passive:true});const started=performance.now();let raf=0;const frame=(now:number)=>{if(!pause)program.uniforms.uTime.value=(now-started)*.001*timeScale;if(pageLoadAnimation)program.uniforms.uLoad.value=Math.min(1,(now-started)/900);renderer.render({scene:mesh});raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);ro.disconnect();host.removeEventListener("pointermove",move);gl.canvas.remove();gl.getExtension("WEBGL_lose_context")?.loseContext();};},[scale,gridMul,digitSize,timeScale,pause,scanlineIntensity,glitchAmount,flickerAmount,noiseAmp,chromaticAberration,dither,curvature,tint,mouseReact,mouseStrength,pageLoadAnimation,brightness]);return <div ref={hostRef} role="img" aria-label="Glitching terminal glyph background" className="relative h-full w-full overflow-hidden rounded-xl"/>;}
