"use client";

// deps: ogl
import { Mesh, Program, Renderer, Triangle } from "ogl";
import { useEffect, useRef } from "react";

export interface GalaxyProps { focal?: [number, number]; rotation?: [number, number]; starSpeed?: number; density?: number; hueShift?: number; disableAnimation?: boolean; speed?: number; mouseInteraction?: boolean; glowIntensity?: number; saturation?: number; mouseRepulsion?: boolean; twinkleIntensity?: number; rotationSpeed?: number; repulsionStrength?: number; autoCenterRepulsion?: number; transparent?: boolean; }
const vertex = `attribute vec2 position; attribute vec2 uv; varying vec2 vUv; void main(){vUv=uv;gl_Position=vec4(position,0.,1.);}`;
const fragment = `precision highp float; varying vec2 vUv; uniform float uTime,uDensity,uHue,uGlow,uSaturation,uTwinkle,uRotationSpeed,uRepulsion,uActive,uCenter; uniform vec2 uResolution,uFocal,uRotation,uMouse; uniform bool uMouseRepulsion,uTransparent; float hash(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);} vec3 hsv(vec3 c){vec4 K=vec4(1.,.666667,.333333,3.);vec3 p=abs(fract(c.xxx+K.xyz)*6.-K.www);return c.z*mix(K.xxx,clamp(p-K.xxx,0.,1.),c.y);} float star(vec2 p,float flare){float d=length(p);float m=.025*uGlow/max(d,.002);m+=smoothstep(1.,0.,abs(p.x*p.y*1000.))*flare*uGlow;m*=smoothstep(.45,0.,d);return m;} vec3 layer(vec2 uv){vec2 id=floor(uv),gv=fract(uv)-.5;vec3 col=vec3(0.);for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){vec2 off=vec2(float(x),float(y)),cell=id+off;float seed=hash(cell),size=fract(seed*345.32);vec2 pad=vec2(hash(cell+1.),hash(cell+3.))-.5;float tw=mix(1.,.65+.35*sin(uTime*2.+seed*30.),uTwinkle);col+=star(gv-off-pad,smoothstep(.88,1.,size))*size*tw*hsv(vec3(fract(seed+uHue/360.),uSaturation,max(.35,seed)));}return col;} void main(){vec2 uv=(vUv-uFocal)*vec2(uResolution.x/uResolution.y,1.);if(uCenter>0.)uv+=normalize(uv+1e-4)*uCenter/(length(uv)+.1)*.05;else if(uMouseRepulsion){vec2 m=(uMouse-uFocal)*vec2(uResolution.x/uResolution.y,1.);uv+=normalize(uv-m+1e-4)*uRepulsion/(length(uv-m)+.1)*.05*uActive;}float a=uTime*uRotationSpeed;uv=mat2(cos(a),-sin(a),sin(a),cos(a))*uv;uv=mat2(uRotation.x,-uRotation.y,uRotation.y,uRotation.x)*uv;vec3 col=vec3(0.);for(float i=0.;i<1.;i+=.25){float depth=fract(i+uTime*.05);col+=layer(uv*mix(20.*uDensity,.5*uDensity,depth)+i*453.32)*depth*smoothstep(1.,.85,depth);}float alpha=smoothstep(0.,.3,length(col));gl_FragColor=vec4(col,uTransparent?alpha:1.);}`;

export function Galaxy({ focal=[.5,.5], rotation=[1,0], starSpeed=.5, density=1, hueShift=140, disableAnimation=false, speed=1, mouseInteraction=true, glowIntensity=.3, saturation=0, mouseRepulsion=true, twinkleIntensity=.3, rotationSpeed=.1, repulsionStrength=2, autoCenterRepulsion=0, transparent=true }: GalaxyProps) {
  const hostRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const host=hostRef.current;if(!host)return;const renderer=new Renderer({dpr:Math.min(2,window.devicePixelRatio||1),alpha:transparent,premultipliedAlpha:false});const gl=renderer.gl;if(transparent){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(0,0,0,0);}const res=new Float32Array(2),mouse=new Float32Array([.5,.5]);const program=new Program(gl,{vertex,fragment,uniforms:{uTime:{value:0},uResolution:{value:res},uFocal:{value:new Float32Array(focal)},uRotation:{value:new Float32Array(rotation)},uDensity:{value:density},uHue:{value:hueShift},uGlow:{value:glowIntensity},uSaturation:{value:saturation},uTwinkle:{value:twinkleIntensity},uRotationSpeed:{value:rotationSpeed},uRepulsion:{value:repulsionStrength},uMouse:{value:mouse},uActive:{value:0},uCenter:{value:autoCenterRepulsion},uMouseRepulsion:{value:mouseRepulsion},uTransparent:{value:transparent}}});const mesh=new Mesh(gl,{geometry:new Triangle(gl),program});Object.assign(gl.canvas.style,{position:"absolute",inset:"0",width:"100%",height:"100%"});host.appendChild(gl.canvas);const resize=()=>{renderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight));res[0]=gl.drawingBufferWidth;res[1]=gl.drawingBufferHeight;};resize();const ro=new ResizeObserver(resize);ro.observe(host);let targetActive=0,active=0,raf=0;const move=(e:PointerEvent)=>{const r=host.getBoundingClientRect();mouse[0]=(e.clientX-r.left)/r.width;mouse[1]=1-(e.clientY-r.top)/r.height;targetActive=1;};const leave=()=>{targetActive=0;};if(mouseInteraction){host.addEventListener("pointermove",move,{passive:true});host.addEventListener("pointerleave",leave);}const started=performance.now();const frame=(now:number)=>{active+=(targetActive-active)*.05;program.uniforms.uActive.value=active;if(!disableAnimation)program.uniforms.uTime.value=(now-started)*.001*speed*starSpeed;renderer.render({scene:mesh});raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);ro.disconnect();host.removeEventListener("pointermove",move);host.removeEventListener("pointerleave",leave);gl.canvas.remove();gl.getExtension("WEBGL_lose_context")?.loseContext();};},[focal,rotation,starSpeed,density,hueShift,disableAnimation,speed,mouseInteraction,glowIntensity,saturation,mouseRepulsion,twinkleIntensity,rotationSpeed,repulsionStrength,autoCenterRepulsion,transparent]);
  return <div ref={hostRef} role="img" aria-label="Animated interactive galaxy background" className="relative h-full w-full overflow-hidden rounded-xl" />;
}
