"use client";

// deps: ogl
import { Mesh, Program, Renderer, Triangle } from "ogl";
import { useEffect, useRef } from "react";

export interface IridescenceProps { color?: [number, number, number]; speed?: number; amplitude?: number; mouseReact?: boolean; }
const vertex=`attribute vec2 position;attribute vec2 uv;varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,0.,1.);}`;
const fragment=`precision highp float;uniform float uTime,uAmplitude,uSpeed;uniform vec3 uColor,uResolution;uniform vec2 uMouse;varying vec2 vUv;void main(){float mr=min(uResolution.x,uResolution.y);vec2 uv=(vUv*2.-1.)*uResolution.xy/mr;uv+=(uMouse-vec2(.5))*uAmplitude;float d=-uTime*.5*uSpeed,a=0.;for(float i=0.;i<8.;i++){a+=cos(i-d-a*uv.x);d+=sin(uv.y*i+a);}d+=uTime*.5*uSpeed;vec3 col=vec3(cos(uv*vec2(d,a))*.6+.4,cos(a+d)*.5+.5);col=cos(col*cos(vec3(d,a,2.5))*.5+.5)*uColor;gl_FragColor=vec4(col,1.);}`;
export function Iridescence({color=[1,1,1],speed=1,amplitude=.1,mouseReact=true}:IridescenceProps){const hostRef=useRef<HTMLDivElement>(null);useEffect(()=>{const host=hostRef.current;if(!host)return;const renderer=new Renderer({dpr:Math.min(2,window.devicePixelRatio||1)}),gl=renderer.gl,res=new Float32Array(3),mouse=new Float32Array([.5,.5]);gl.clearColor(1,1,1,1);const program=new Program(gl,{vertex,fragment,uniforms:{uTime:{value:0},uColor:{value:new Float32Array(color)},uResolution:{value:res},uMouse:{value:mouse},uAmplitude:{value:amplitude},uSpeed:{value:speed}}});const mesh=new Mesh(gl,{geometry:new Triangle(gl),program});Object.assign(gl.canvas.style,{position:"absolute",inset:"0",width:"100%",height:"100%"});host.appendChild(gl.canvas);const resize=()=>{renderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight));res[0]=gl.drawingBufferWidth;res[1]=gl.drawingBufferHeight;res[2]=res[0]/res[1];};resize();const ro=new ResizeObserver(resize);ro.observe(host);const move=(event:PointerEvent)=>{const rect=host.getBoundingClientRect();mouse[0]=(event.clientX-rect.left)/rect.width;mouse[1]=1-(event.clientY-rect.top)/rect.height;};if(mouseReact)host.addEventListener("pointermove",move,{passive:true});let raf=0;const frame=(now:number)=>{program.uniforms.uTime.value=now*.001;renderer.render({scene:mesh});raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);ro.disconnect();host.removeEventListener("pointermove",move);gl.canvas.remove();gl.getExtension("WEBGL_lose_context")?.loseContext();};},[color,speed,amplitude,mouseReact]);return <div ref={hostRef} role="img" aria-label="Animated iridescent color background" className="relative h-full w-full overflow-hidden rounded-xl"/>;}
