"use client";

// deps: three
import { useEffect, useRef } from "react";
import * as THREE from "three";

export type PixelSnowVariant = "square" | "round" | "snowflake";
export interface PixelSnowProps { color?: string; flakeSize?: number; minFlakeSize?: number; pixelResolution?: number; speed?: number; depthFade?: number; farPlane?: number; brightness?: number; gamma?: number; density?: number; variant?: PixelSnowVariant; direction?: number; }
const vertex=`void main(){gl_Position=vec4(position,1.);}`;
const fragment=`precision highp float;uniform vec2 uResolution;uniform vec3 uColor;uniform float uTime,uSize,uPixel,uSpeed,uFade,uBrightness,uDensity,uVariant,uDirection;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){float block=max(1.,floor(uResolution.x/max(uPixel,1.)));vec2 p=floor(gl_FragCoord.xy/block)*block;vec2 uv=p/uResolution;vec3 col=vec3(0.);float angle=radians(uDirection);vec2 wind=vec2(cos(angle),sin(angle))*.12*uTime*uSpeed;for(float layer=0.;layer<4.;layer++){float scale=mix(18.,90.,layer/3.);vec2 grid=(uv+wind*(.3+layer*.25))*scale;vec2 id=floor(grid),cell=fract(grid)-.5;float seed=hash(id+layer*71.);if(seed<uDensity){vec2 drift=vec2(sin(uTime*uSpeed+seed*20.),cos(uTime*uSpeed*.7+seed*10.))*.16;float r=mix(.08,.26,seed)*uSize*100.;float d=uVariant<.5?max(abs(cell.x+drift.x),abs(cell.y+drift.y)):length(cell+drift);if(uVariant>1.5){float spokes=abs(sin(atan(cell.y,cell.x)*6.));d=min(d,abs(length(cell)-r*.9+spokes*.03));}float flake=1.-smoothstep(r,r+.018,d);col+=uColor*flake*(1.-layer*.18)*uBrightness;} }gl_FragColor=vec4(col,clamp(length(col),0.,1.));}`;
export function PixelSnow({color="#ffffff",flakeSize=.01,minFlakeSize=1.25,pixelResolution=200,speed=1.25,depthFade=8,farPlane=20,brightness=1,gamma=.4545,density=.3,variant="square",direction=125}:PixelSnowProps){const hostRef=useRef<HTMLDivElement>(null);useEffect(()=>{const host=hostRef.current;if(!host)return;const renderer=new THREE.WebGLRenderer({alpha:true,antialias:false,premultipliedAlpha:false,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setClearColor(0,0);renderer.domElement.className="block h-full w-full";host.appendChild(renderer.domElement);const uniforms={uResolution:{value:new THREE.Vector2(1,1)},uColor:{value:new THREE.Color(color)},uTime:{value:0},uSize:{value:flakeSize},uPixel:{value:pixelResolution},uSpeed:{value:speed},uFade:{value:depthFade},uBrightness:{value:brightness},uDensity:{value:density},uVariant:{value:variant==="round"?1:variant==="snowflake"?2:0},uDirection:{value:direction}};const material=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,uniforms,transparent:true,depthTest:false,depthWrite:false});const geometry=new THREE.PlaneGeometry(2,2),scene=new THREE.Scene(),camera=new THREE.Camera();scene.add(new THREE.Mesh(geometry,material));const resize=()=>{renderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight),false);uniforms.uResolution.value.set(renderer.domElement.width,renderer.domElement.height);};resize();const ro=new ResizeObserver(resize);ro.observe(host);const started=performance.now();let raf=0;const frame=(now:number)=>{uniforms.uTime.value=(now-started)*.001;renderer.render(scene,camera);raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);ro.disconnect();geometry.dispose();material.dispose();renderer.dispose();renderer.domElement.remove();};},[color,flakeSize,minFlakeSize,pixelResolution,speed,depthFade,farPlane,brightness,gamma,density,variant,direction]);return <div ref={hostRef} role="img" aria-label="Animated pixel snow background" className="relative h-full w-full overflow-hidden rounded-xl"/>;}
