"use client";

// deps: ogl
import { useEffect, useRef } from "react";
import { Mesh, Program, Renderer, Triangle } from "ogl";

export type PrismAnimation = "rotate" | "hover" | "3drotate";
export interface PrismProps { height?: number; baseWidth?: number; animationType?: PrismAnimation; glow?: number; noise?: number; transparent?: boolean; scale?: number; hueShift?: number; colorFrequency?: number; hoverStrength?: number; inertia?: number; bloom?: number; suspendWhenOffscreen?: boolean; timeScale?: number; }

const vertex = `attribute vec2 position; void main(){gl_Position=vec4(position,0.,1.);}`;
const fragment = `precision highp float; uniform vec2 uResolution; uniform float uTime,uHeight,uBaseHalf,uGlow,uNoise,uScale,uHue,uFrequency,uBloom; uniform mat3 uRotation; float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);} vec4 tnh(vec4 x){vec4 e=exp(2.*x);return(e-1.)/(e+1.);} float pyramid(vec3 p){vec3 q=vec3(abs(p.x)/uBaseHalf,abs(p.y)/uHeight,abs(p.z)/uBaseHalf);return max(q.x+q.y+q.z-1.,-p.y/uHeight)*min(uBaseHalf,uHeight)*.57735;} mat3 hue(float a){float c=cos(a),s=sin(a);return mat3(.299+.701*c+.168*s,.587-.587*c-.331*s,.114-.114*c+.5*s,.299-.299*c+.328*s,.587+.413*c+.035*s,.114-.114*c-.5*s,.299-.3*c-.497*s,.587-.588*c+.296*s,.114+.886*c+.201*s);} void main(){vec2 uv=(gl_FragCoord.xy-.5*uResolution)/(max(uResolution.y,1.)*.1*max(uScale,.001));float z=5.;vec4 o=vec4(0.);for(int i=0;i<88;i++){vec3 p=uRotation*vec3(uv,z);p.y+=uHeight*.25;float d=.09+.21*abs(pyramid(p));z-=d;o+=(sin((p.y+z)*uFrequency+vec4(0.,1.,2.,3.))+1.)/d;}o=tnh(o*o*uGlow*max(uBloom,0.)/90000.);vec3 col=clamp(hue(uHue)*o.rgb,0.,1.);col+=(h(gl_FragCoord.xy+uTime)-.5)*uNoise;gl_FragColor=vec4(clamp(col,0.,1.),o.a);}`;

export function Prism({ height=3.5, baseWidth=5.5, animationType="rotate", glow=1, noise=.5, transparent=true, scale=3.6, hueShift=0, colorFrequency=1, hoverStrength=2, inertia=.05, bloom=1, suspendWhenOffscreen=false, timeScale=.5 }: PrismProps) {
  const hostRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const host=hostRef.current; if(!host) return; const renderer=new Renderer({dpr:Math.min(2,window.devicePixelRatio||1),alpha:transparent,antialias:false}); const gl=renderer.gl; gl.disable(gl.DEPTH_TEST); gl.disable(gl.CULL_FACE); gl.disable(gl.BLEND); Object.assign(gl.canvas.style,{position:"absolute",inset:"0",display:"block",width:"100%",height:"100%"}); host.appendChild(gl.canvas);
    const res=new Float32Array(2), rot=new Float32Array([1,0,0,0,1,0,0,0,1]); const program=new Program(gl,{vertex,fragment,uniforms:{uResolution:{value:res},uTime:{value:0},uHeight:{value:Math.max(.001,height)},uBaseHalf:{value:Math.max(.001,baseWidth)*.5},uGlow:{value:Math.max(0,glow)},uNoise:{value:Math.max(0,noise)},uScale:{value:Math.max(.001,scale)},uHue:{value:hueShift},uFrequency:{value:Math.max(0,colorFrequency)},uBloom:{value:Math.max(0,bloom)},uRotation:{value:rot}}}); const mesh=new Mesh(gl,{geometry:new Triangle(gl),program});
    const resize=()=>{renderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight));res[0]=gl.drawingBufferWidth;res[1]=gl.drawingBufferHeight;}; resize(); const ro=new ResizeObserver(resize); ro.observe(host); const setRot=(y:number,x:number,z:number)=>{const cy=Math.cos(y),sy=Math.sin(y),cx=Math.cos(x),sx=Math.sin(x),cz=Math.cos(z),sz=Math.sin(z);rot.set([cy*cz+sy*sx*sz,cx*sz,-sy*cz+cy*sx*sz,-cy*sz+sy*sx*cz,cx*cz,sy*sz+cy*sx*cz,sy*cx,-sx,cy*cx]);};
    let tx=0,ty=0,yaw=0,pitch=0,raf=0,visible=true; const move=(e:PointerEvent)=>{if(animationType==="hover"){tx=((e.clientX/window.innerWidth)*2-1)*hoverStrength*.6;ty=((e.clientY/window.innerHeight)*2-1)*hoverStrength*.6;}}; window.addEventListener("pointermove",move,{passive:true}); const started=performance.now(); const frame=(now:number)=>{if(!visible){raf=requestAnimationFrame(frame);return;}const t=(now-started)*.001*Math.max(0,timeScale);program.uniforms.uTime.value=t;if(animationType==="hover"){yaw+=(-tx-yaw)*inertia;pitch+=(ty-pitch)*inertia;setRot(yaw,pitch,0);}else if(animationType==="3drotate")setRot(t*.55,Math.sin(t*.37)*.6,Math.sin(t*.21)*.45);else setRot(0,0,0);renderer.render({scene:mesh});if(timeScale>0||animationType==="hover")raf=requestAnimationFrame(frame);}; const io=suspendWhenOffscreen?new IntersectionObserver(([entry])=>{visible=Boolean(entry?.isIntersecting);}):undefined;io?.observe(host);raf=requestAnimationFrame(frame);
    return()=>{cancelAnimationFrame(raf);ro.disconnect();io?.disconnect();window.removeEventListener("pointermove",move);gl.canvas.remove();};
  },[height,baseWidth,animationType,glow,noise,transparent,scale,hueShift,colorFrequency,hoverStrength,inertia,bloom,suspendWhenOffscreen,timeScale]);
  return <div ref={hostRef} role="img" aria-label="Animated luminous prism background" className="relative h-full w-full overflow-hidden rounded-xl" />;
}
