"use client";

import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { useMemo, useRef } from "react";
import * as THREE from "three";

const seededNoise = (seed: number) => { const value = Math.sin(seed) * 43758.5453123; return value - Math.floor(value); };

export interface AntigravityProps { count?: number; magnetRadius?: number; ringRadius?: number; waveSpeed?: number; waveAmplitude?: number; particleSize?: number; lerpSpeed?: number; color?: string; autoAnimate?: boolean; particleVariance?: number; rotationSpeed?: number; depthFactor?: number; pulseSpeed?: number; particleShape?: "capsule" | "sphere" | "box" | "tetrahedron"; fieldStrength?: number; }

function AntigravityInner({ count = 300, magnetRadius = 10, ringRadius = 10, waveSpeed = .4, waveAmplitude = 1, particleSize = 2, lerpSpeed = .1, color = "#FF9FFC", autoAnimate = false, particleVariance = 1, rotationSpeed = 0, depthFactor = 1, pulseSpeed = 3, particleShape = "capsule", fieldStrength = 10 }: AntigravityProps) {
  const meshRef = useRef<THREE.InstancedMesh>(null); const { viewport } = useThree(); const dummy = useMemo(() => new THREE.Object3D(), []); const virtualMouse = useRef({ x: 0, y: 0 }); const lastMouse = useRef({ x: 0, y: 0, time: 0 });
  const particles = useMemo(() => Array.from({ length: count }, (_, index) => { const seed = index * 97.17 + viewport.width * 13.1 + viewport.height * 29.3, random = (offset: number) => seededNoise(seed + offset); const x = (random(1) - .5) * viewport.width, y = (random(2) - .5) * viewport.height, z = (random(3) - .5) * 20; return { t: random(4) * 100, speed: .01 + random(5) / 200, mx: x, my: y, mz: z, cx: x, cy: y, cz: z, offset: (random(6) - .5) * 2 }; }), [count, viewport.width, viewport.height]);
  useFrame((state) => { const mesh = meshRef.current; if (!mesh) return; const pointer = state.pointer, moved = Math.hypot(pointer.x - lastMouse.current.x, pointer.y - lastMouse.current.y); if (moved > .001) lastMouse.current = { x: pointer.x, y: pointer.y, time: Date.now() }; let destinationX = pointer.x * viewport.width / 2, destinationY = pointer.y * viewport.height / 2; if (autoAnimate && Date.now() - lastMouse.current.time > 2000) { const time = state.clock.getElapsedTime(); destinationX = Math.sin(time * .5) * viewport.width / 4; destinationY = Math.cos(time) * viewport.height / 4; } virtualMouse.current.x += (destinationX - virtualMouse.current.x) * .05; virtualMouse.current.y += (destinationY - virtualMouse.current.y) * .05; const time = state.clock.getElapsedTime(), rotation = time * rotationSpeed;
    particles.forEach((particle, index) => { particle.t += particle.speed / 2; const projection = 1 - particle.cz / 50, targetX = virtualMouse.current.x * projection, targetY = virtualMouse.current.y * projection, dx = particle.mx - targetX, dy = particle.my - targetY, distance = Math.hypot(dx, dy); let x = particle.mx, y = particle.my, z = particle.mz * depthFactor; if (distance < magnetRadius) { const angle = Math.atan2(dy, dx) + rotation, wave = Math.sin(particle.t * waveSpeed + angle) * .5 * waveAmplitude, radius = ringRadius + wave + particle.offset * (5 / (fieldStrength + .1)); x = targetX + radius * Math.cos(angle); y = targetY + radius * Math.sin(angle); z = particle.mz * depthFactor + Math.sin(particle.t) * waveAmplitude * depthFactor; } particle.cx += (x - particle.cx) * lerpSpeed; particle.cy += (y - particle.cy) * lerpSpeed; particle.cz += (z - particle.cz) * lerpSpeed; dummy.position.set(particle.cx, particle.cy, particle.cz); dummy.lookAt(targetX, targetY, particle.cz); dummy.rotateX(Math.PI / 2); const ringDistance = Math.abs(Math.hypot(particle.cx - targetX, particle.cy - targetY) - ringRadius), scale = Math.max(0, Math.min(1, 1 - ringDistance / 10)) * (.8 + Math.sin(particle.t * pulseSpeed) * .2 * particleVariance) * particleSize; dummy.scale.setScalar(scale); dummy.updateMatrix(); mesh.setMatrixAt(index, dummy.matrix); }); mesh.instanceMatrix.needsUpdate = true; });
  return <instancedMesh ref={meshRef} args={[undefined, undefined, count]}>{particleShape === "capsule" && <capsuleGeometry args={[.1, .4, 4, 8]} />}{particleShape === "sphere" && <sphereGeometry args={[.2, 16, 16]} />}{particleShape === "box" && <boxGeometry args={[.3, .3, .3]} />}{particleShape === "tetrahedron" && <tetrahedronGeometry args={[.3]} />}<meshBasicMaterial color={color} /></instancedMesh>;
}

export function Antigravity(props: AntigravityProps) { return <div className="h-[380px] w-full overflow-hidden rounded-2xl bg-slate-950"><Canvas camera={{ position: [0, 0, 50], fov: 35 }}><AntigravityInner {...props} /></Canvas></div>; }
