"use client";

/* eslint-disable react/no-unknown-property */
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { useMemo, useRef } from "react";
import * as THREE from "three";

type GlassMaterialProps = { color?: THREE.ColorRepresentation; roughness?: number; transmission?: number; ior?: number; thickness?: number; chromaticAberration?: number; scale?: number };
export interface FluidGlassProps { mode?: "lens" | "bar" | "cube"; lensProps?: GlassMaterialProps; barProps?: GlassMaterialProps; cubeProps?: GlassMaterialProps; }

function Backdrop() { const material = useMemo(() => new THREE.MeshBasicMaterial({ color: "#5227ff" }), []); return <><color attach="background" args={["#161128"]} /><mesh position={[0, 0, -2]} scale={[30, 20, 1]} material={material}><planeGeometry /></mesh><mesh position={[-3.5, 1.5, -1]} rotation={[.3, .4, 0]}><icosahedronGeometry args={[2.4, 3]} /><meshBasicMaterial color="#ff9ffc" wireframe /></mesh><mesh position={[3.3, -1.2, -1]} rotation={[-.2, -.35, 0]}><torusKnotGeometry args={[1.4, .35, 120, 16]} /><meshBasicMaterial color="#7df9ff" wireframe /></mesh></>; }
function GlassObject({ mode, options }: { mode: NonNullable<FluidGlassProps["mode"]>; options: GlassMaterialProps }) { const ref = useRef<THREE.Mesh>(null); const { viewport } = useThree(); useFrame((state, delta) => { if (!ref.current) return; const x = state.pointer.x * viewport.width / 5, y = state.pointer.y * viewport.height / 5; ref.current.position.lerp(new THREE.Vector3(x, y, 0), 1 - Math.exp(-delta * 6)); ref.current.rotation.x = state.clock.elapsedTime * .15; ref.current.rotation.y = state.clock.elapsedTime * .22; }); const material = { color: options.color ?? "#ffffff", roughness: options.roughness ?? .05, transmission: options.transmission ?? 1, ior: options.ior ?? 1.15, thickness: options.thickness ?? 3, transparent: true, opacity: .92 }; const scale = options.scale ?? (mode === "bar" ? 2.2 : 1.5); return <mesh ref={ref} scale={scale}>{mode === "lens" && <sphereGeometry args={[1, 64, 64]} />}{mode === "bar" && <boxGeometry args={[2.7, .42, .36, 8, 4, 4]} />}{mode === "cube" && <boxGeometry args={[1.25, 1.25, 1.25, 8, 8, 8]} />}<meshPhysicalMaterial {...material} /></mesh>; }
function Scene({ mode, options }: { mode: NonNullable<FluidGlassProps["mode"]>; options: GlassMaterialProps }) { return <><ambientLight intensity={1.3} /><pointLight position={[3, 3, 4]} color="#ffffff" intensity={25} /><pointLight position={[-4, -2, 3]} color="#ff9ffc" intensity={18} /><Backdrop /><GlassObject mode={mode} options={options} /></>; }
export function FluidGlass({ mode = "lens", lensProps = {}, barProps = {}, cubeProps = {} }: FluidGlassProps) { const options = mode === "bar" ? barProps : mode === "cube" ? cubeProps : lensProps; return <div className="h-[380px] w-full overflow-hidden rounded-2xl bg-[#161128]"><Canvas camera={{ position: [0, 0, 9], fov: 38 }} dpr={[1, 2]} gl={{ alpha: false, antialias: true }}><Scene mode={mode} options={options} /></Canvas></div>; }
